# Generated by Django 3.0.5 on 2020-05-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200502_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Name',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
