# Generated by Django 3.0.5 on 2020-05-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
